name: CI
on:
  push:
    branches: [master]
    tags: ['v*']
  pull_request: { branches: [master] }
  schedule: [ cron: '5 1 5 * *' ]

jobs:
  test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install man-db- libperl-critic-perl
      - run: perlcritic diff-logs
      - run: echo '2000-01-01T00:00:00' > file.log
      - run: time ./diff-logs < file.log
      - run: time ./diff-logs file.log file.log
      - run: time tests/test.sh
      - run: podman run -v.:/src ubuntu:latest /src/tests/test.sh  # Runs on base container

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c  # v1.2.1
